
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'databricks_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']


vars:
  # Ref: https://docs.getdbt.com/guides/migration/versions/upgrading-to-dbt-utils-v1.0#changes-to-surrogate_key
  surrogate_key_treat_nulls_as_empty_strings: true

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +persist_docs:
    relation: true
    columns: true
  databricks_demo:
    # Applies to all files under models/example/
    staging:
      +materialized: view
      airbnb:
        +enabled: false
    marts:
      +materialized: table
      file_format: delta
      ml:
        +cluster_id: "{{ env_var('DBT_DATABRICKS_CLUSTER_ID') }}"
        +submission_method: all_purpose_cluster

        # Disabled until https://github.com/databricks/dbt-databricks/issues/232 is resolved
        +enabled: true
      airbnb:
        +enabled: false
vars:
  surrogate_key_treat_nulls_as_empty_strings: true 
